DROP DATABASE IF EXISTS comercio;
CREATE DATABASE IF NOT exists comercio;

use COMERCIO;

-- show DATABASES;

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY AUTO_INCREMENT, 
NOME VARCHAR(50) NOT NULL,
SEXO ENUM('M', 'F') NOT NULL,
email varchar(50) UNIQUE,
CPF VARCHAR(15) unique
);

CREATE TABLE endereco(
idEndereco INT PRIMARY KEY AUTO_INCREMENT,
rua VARCHAR(50) NOT NULL, 
bairro VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL, 
ESTADO CHAR(2) NOT NULL,
fkCliente INT UNIQUE,
FOREIGN KEY (fkCliente) 
REFERENCES cliente (idCliente)
);

create TABLE TELEFONE (
idTelefone INT PRIMARY KEY AUTO_INCREMENT,
tipo ENUM('RES', 'COM', 'CEL') not null,
numero varchar(11),
fkCliente INT,
FOREIGN KEY (fkCliente)
REFERENCES cliente (idCliente)
);

INSERT INTO CLIENTE VALUES(NULL, 'Eder', 'M', 'EDER@EMAIL.COM', '11111111111');
INSERT INTO CLIENTE VALUES(NULL, 'Maria', 'F', 'maria@email.com', '22222222222');
INSERT INTO CLIENTE VALUES(NULL, 'João', 'M', NULL, '33333333333');
INSERT INTO CLIENTE VALUES(NULL, 'Ana', 'F', 'ana@email.com', '44444444444');
INSERT INTO CLIENTE VALUES(NULL, 'Carlos', 'M', 'carlos@email.com', '55555555555');
INSERT INTO CLIENTE VALUES(NULL, 'Mariana', 'F', 'mariana@email.com', '66666666666');
INSERT INTO CLIENTE VALUES(NULL, 'Pedro', 'M', 'pedro@email.com', '77777777777');
INSERT INTO CLIENTE VALUES(NULL, 'Isabel', 'F', 'isabel@email.com', '88888888888');
INSERT INTO CLIENTE VALUES(NULL, 'Ricardo', 'M', 'ricardo@email.com', '99999999999');
INSERT INTO CLIENTE VALUES(NULL, 'Fernanda', 'F', 'fernanda@email.com', '10101010101');

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE', 'MG', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA BELA VISTA', 'JARDIM', 'SAO PAULO', 'SP', 1);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA BRASIL', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DA LIBERDADE', 'LIBERDADE', 'SAO PAULO', 'SP', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DAS FLORES', 'FLORES', 'CAMPINAS', 'SP', 5);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA PAULISTA', 'BELA VISTA', 'SAO PAULO', 'SP', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DOS ARTISTAS', 'ARTISTAS', 'SALVADOR', 'BA', 7);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA AMAZONAS', 'AMAZONAS', 'BELO HORIZONTE', 'MG', 8);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DA REPÚBLICA', 'REPÚBLICA', 'CURITIBA', 'PR', 9);

INSERT INTO telefone VALUES (NULL, 'CEL', '123213441', 1);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '1122334455', 2);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9988776655', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9876543210', 4);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '1122334455', 5);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9988776655', 6);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '9876543210', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9923376655', 6);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9876543210', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '1122334455', 4);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9988776655', 3);

/*
	DML - DATA MANIPULATION LANGUAGE
    DDL - DATA DEFINITION LANGUAGE
    DCL - DATA CONTROL LANGUAGEL
    TCL - TRANSACTION CONTROL LANGUAGE

*/

/* INSERT */

INSERT INTO CLIENTE VALUES(NULL,'PAULA','M',NULL,'77437493');

SELECT * FROM CLIENTE;

/* FILTROS */

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/* UPDATE */

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

/* DELETE */ 

INSERT INTO CLIENTE VALUES(NULL,'XXX','M',NULL,'XXX');

SELECT * FROM CLIENTE
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE WHERE IDCLIENTE = 10;

/* 
  DDL - DATA DEFINITION LANGUAGE
*/

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME_PRODUTO VARCHAR(30) NOT NULL,
	PRECO INT,
	FRETE FLOAT(10,2) NOT NULL
);

/* ALTER TABLE */


/* Alterando o nome de uma tabela - Change */

ALTER TABLE PRODUTO CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

/* Modify */

ALTER TABLE PRODUTO MODIFY VALOR_UNITARIO VARCHAR(30);

DESC PRODUTO;

/* Adicionando colunas */

ALTER TABLE PRODUTO ADD PESO FLOAT(10,2) NOT NULL; 
DESC PRODUTO;
/* apagando uma coluna */

ALTER TABLE PRODUTO DROP COLUMN PESO;  
DESC PRODUTO;

/* Adicionado coluna em orde especifica */

ALTER TABLE PRODUTO ADD PESO FLOAT(10,2) NOT NULL AFTER NOME_PRODUTO;
DESC PRODUTO;