DROP DATABASE IF EXISTS comercio;
CREATE DATABASE IF NOT exists comercio;

use COMERCIO;

-- show DATABASES;

CREATE TABLE CLIENTE(
idCliente INT PRIMARY KEY AUTO_INCREMENT, 
NOME VARCHAR(50) NOT NULL,
SEXO ENUM('M', 'F') NOT NULL,
email varchar(50) UNIQUE,
CPF VARCHAR(15) unique
);

CREATE TABLE endereco(
idEndereco INT PRIMARY KEY AUTO_INCREMENT,
rua VARCHAR(50) NOT NULL, 
bairro VARCHAR(50) NOT NULL,
CIDADE VARCHAR(50) NOT NULL, 
ESTADO CHAR(2) NOT NULL,
fkCliente INT UNIQUE,
FOREIGN KEY (fkCliente) 
REFERENCES cliente (idCliente)
);

create TABLE TELEFONE (
idTelefone INT PRIMARY KEY AUTO_INCREMENT,
tipo ENUM('RES', 'COM', 'CEL') not null,
numero varchar(11),
fkCliente INT,
FOREIGN KEY (fkCliente)
REFERENCES cliente (idCliente)
);

-- SHOW TABLES;
/* Endereco - Obrigatorio
Cadastro de somente um.

Telefone - Nao Obrigatorio
CADASTRO DE MAIS DE UM (OPCIONAL) /* 

/* 
Chave estrageinra é a chave primaria de um tabela que vai ate a outra tabela
para fazer referencia entre registros */

/* Em relacionamento 1 x 1, a chave estrangeira fica na tabela mais fraca */
/* Em relacionamento 1 X N, a chave estrangeira fica sempre na cardinalidade N */

INSERT INTO CLIENTE VALUES(NULL, 'Eder', 'M', 'EDER@EMAIL.COM', '11111111111');
INSERT INTO CLIENTE VALUES(NULL, 'Maria', 'F', 'maria@email.com', '22222222222');
INSERT INTO CLIENTE VALUES(NULL, 'João', 'M', NULL, '33333333333');
INSERT INTO CLIENTE VALUES(NULL, 'Ana', 'F', 'ana@email.com', '44444444444');
INSERT INTO CLIENTE VALUES(NULL, 'Carlos', 'M', 'carlos@email.com', '55555555555');
INSERT INTO CLIENTE VALUES(NULL, 'Mariana', 'F', 'mariana@email.com', '66666666666');
INSERT INTO CLIENTE VALUES(NULL, 'Pedro', 'M', 'pedro@email.com', '77777777777');
INSERT INTO CLIENTE VALUES(NULL, 'Isabel', 'F', 'isabel@email.com', '88888888888');
INSERT INTO CLIENTE VALUES(NULL, 'Ricardo', 'M', 'ricardo@email.com', '99999999999');
INSERT INTO CLIENTE VALUES(NULL, 'Fernanda', 'F', 'fernanda@email.com', '10101010101');

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE', 'MG', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA BELA VISTA', 'JARDIM', 'SAO PAULO', 'SP', 1);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA BRASIL', 'CENTRO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DA LIBERDADE', 'LIBERDADE', 'SAO PAULO', 'SP', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DAS FLORES', 'FLORES', 'CAMPINAS', 'SP', 5);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA PAULISTA', 'BELA VISTA', 'SAO PAULO', 'SP', 6);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DOS ARTISTAS', 'ARTISTAS', 'SALVADOR', 'BA', 7);
INSERT INTO ENDERECO VALUES (NULL, 'AVENIDA AMAZONAS', 'AMAZONAS', 'BELO HORIZONTE', 'MG', 8);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DA REPÚBLICA', 'REPÚBLICA', 'CURITIBA', 'PR', 9);

INSERT INTO telefone VALUES (NULL, 'CEL', '123213441', 1);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '1122334455', 2);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9988776655', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9876543210', 4);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '1122334455', 5);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9988776655', 6);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '9876543210', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9923376655', 6);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '9876543210', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '1122334455', 4);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '9988776655', 3);

/* SELECAO, PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER VER NA TELA */

-- SELECT NOW() AS DATA_ATUAL;

-- SELECT 2 + 2 AS SOMA;

-- SELECT 2 + 2 AS SOMA, NOME, NOW()
-- FROM CLIENTE;

/* SELECAO -> É UM SUBCONJUNTO DO CONJUNTO TOTAL DE REGISTROS DE UMA TABELA
A CLAUSULA DE SELECAO É O WHERE
*/


-- SELECT NOME, SEXO, EMAIL /* PROJECAO */
-- FROM CLIENTE /* ORIGEM */
-- WHERE SEXO = 'F'; /* SELECAO */


-- SELECT NUMERO /* PROJECAO */
-- FROM TELEFONE /* ORIGEM */
-- WHERE TIPO = 'CEL'; /* SELECAO */


/* JUNCAO -> JOIN */

-- Seleciona os campos NOME, EMAIL e IDCLIENTE da tabela CLIENTE
SELECT NOME, EMAIL, IDCLIENTE FROM CLIENTE;

-- Seleciona os campos fkCLIENTE, BAIRRO e CIDADE da tabela ENDERECO
SELECT fkCLIENTE, BAIRRO, CIDADE FROM ENDERECO;



-- Seleciona os campos NOME, SEXO, BAIRRO e CIDADE da tabela CLIENTE e ENDERECO
SELECT NOME, SEXO, BAIRRO, CIDADE
-- Junção entre CLIENTE e ENDERECO usando IDCLIENTE e fkCliente
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = fkCliente; -- Condição de junção



SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE, ENDERECO WHERE IDCLIENTE = FKCLIENTE AND SEXO = 'F';

SELECT NOME, SEXO, BAIRRO, CIDADE FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = FKCLIENTE;

SELECT NOME, SEXO, BAIRRO, CIDADE FROM -- Projecao
 CLIENTE INNER JOIN -- Origem
 ENDERECO ON IDCLIENTE = FKCLIENTE  
 WHERE SEXO = 'F'; -- Selecao
 
 SELECT NOME, SEXO, EMAIL, TIPO, NUMERO FROM CLIENTE INNER JOIN TELEFONE ON IDCLIENTE = FKCLIENTE;

-- Seleciona os campos NOME, SEXO, BAIRRO, CIDADE, TIPO e NUMERO da tabela CLIENTE, ENDERECO e TELEFONE
SELECT NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
-- Junções INNER JOIN entre CLIENTE, ENDERECO e TELEFONE usando IDCLIENTE e FKCLIENTE
FROM CLIENTE c
INNER JOIN ENDERECO e ON c.IDCLIENTE = e.FKCLIENTE 
INNER JOIN TELEFONE t ON c.IDCLIENTE = t.FKCLIENTE;































